---
language: elixir
elixir:
  - 1.3.2
env:
  - TRAVIS_NODE_VERSION="5.11"
otp_release:
  - 18.0
sudo: false # to use faster container based build environment
addons:
  postgresql: "9.4"
before_install:
  - cp config/dev.secret.example.exs config/dev.secret.exs
  - cp config/test.secret.example.exs config/test.secret.exs
before_script:
  - MIX_ENV=test mix ecto.create
script: MIX_ENV=test mix do compile --warning-as-errors, test
cache:
  directories:
    - _build
    - deps
